
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jMenu1 = new javax.swing.JMenu();
        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        genderGroup = new javax.swing.ButtonGroup();
        age = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        nextInfo = new javax.swing.JButton();
        myTabs = new javax.swing.JTabbedPane();
        Language = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        English = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Greek = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SignIn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Continue1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        gmailAPI = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SignInGreek = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Continue2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        InfosGr = new javax.swing.JPanel();
        usernameGr = new javax.swing.JLabel();
        userIn = new javax.swing.JTextField();
        maleGr = new javax.swing.JRadioButton();
        femaleGr = new javax.swing.JRadioButton();
        otherGr = new javax.swing.JRadioButton();
        ageGr = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Next1 = new javax.swing.JButton();
        birth = new javax.swing.JLabel();
        genderGr = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        InfosEn = new javax.swing.JPanel();
        usernameEn = new javax.swing.JLabel();
        UserIn2 = new javax.swing.JTextField();
        otherEn = new javax.swing.JRadioButton();
        maleEn = new javax.swing.JRadioButton();
        womanEn = new javax.swing.JRadioButton();
        ageEn = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        Next2 = new javax.swing.JButton();
        age2 = new javax.swing.JLabel();
        genderEn = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jPasswordField1.setText("jPasswordField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox1.setText("jCheckBox1");

        age.setText("...");

        jLabel3.setText("Age:");

        username.setText("Username: ");

        user.setText("...");

        jLabel8.setText("Gender:");

        genderGroup.add(male);
        male.setText("Male");

        genderGroup.add(female);
        female.setText("Female");

        genderGroup.add(other);
        other.setText("Other");

        nextInfo.setText("Next >>");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ExceDriving: Practical Exam Simulator !");
        setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(0, 51, 0));
        setMinimumSize(new java.awt.Dimension(830, 680));
        setPreferredSize(new java.awt.Dimension(870, 588));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myTabs.setMinimumSize(new java.awt.Dimension(870, 580));
        myTabs.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                myTabsComponentHidden(evt);
            }
        });

        Language.setMinimumSize(new java.awt.Dimension(830, 680));
        Language.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\eng.png")); // NOI18N
        Language.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 60, 50));

        English.setBackground(new java.awt.Color(153, 255, 102));
        English.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        English.setForeground(new java.awt.Color(255, 255, 255));
        English.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        English.setText("English");
        English.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 3, true));
        English.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        English.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        English.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dark.jpg")); // NOI18N
        English.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        English.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EnglishStateChanged(evt);
            }
        });
        English.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnglishFocusGained(evt);
            }
        });
        English.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishActionPerformed(evt);
            }
        });
        Language.add(English, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 260, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\gr.png")); // NOI18N
        Language.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 60, 50));

        Greek.setBackground(new java.awt.Color(255, 255, 255));
        Greek.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        Greek.setForeground(new java.awt.Color(255, 255, 255));
        Greek.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Greek.setText("Ελληνικά");
        Greek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 3, true));
        Greek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Greek.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Greek.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dark.jpg")); // NOI18N
        Greek.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Greek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreekActionPerformed(evt);
            }
        });
        Language.add(Greek, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 260, 67));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\FullLogo.jpg")); // NOI18N
        Language.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -20, 1050, 990));

        myTabs.addTab("Language", Language);

        SignIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 24)); // NOI18N
        jLabel1.setText("Please, sign in to continue:");
        SignIn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 320, 40));

        Continue1.setBackground(new java.awt.Color(153, 255, 102));
        Continue1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Continue1.setForeground(new java.awt.Color(255, 255, 255));
        Continue1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Continue1.setText("Continue");
        Continue1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 3, true));
        Continue1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Continue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Continue1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dark.jpg")); // NOI18N
        Continue1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Continue1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Continue1StateChanged(evt);
            }
        });
        Continue1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Continue1FocusGained(evt);
            }
        });
        Continue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Continue1ActionPerformed(evt);
            }
        });
        SignIn.add(Continue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 140, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\googler.png")); // NOI18N
        SignIn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 40, 40));

        gmailAPI.setBackground(new java.awt.Color(184, 187, 185));
        gmailAPI.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        gmailAPI.setText("  Google Account ");
        gmailAPI.setBorder(null);
        gmailAPI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gmailAPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmailAPIActionPerformed(evt);
            }
        });
        SignIn.add(gmailAPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 260, 60));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\FullLogo.jpg")); // NOI18N
        SignIn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 920, 960));

        myTabs.addTab("Sign in", SignIn);

        SignInGreek.setMinimumSize(new java.awt.Dimension(800, 400));
        SignInGreek.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Παρακαλώ, συνδεθείτε για να συνεχίσετε:");
        SignInGreek.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 430, 32));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\googler.png")); // NOI18N
        SignInGreek.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 40, 50));

        jButton3.setBackground(new java.awt.Color(184, 187, 185));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jButton3.setText("Google Account");
        jButton3.setBorder(null);
        SignInGreek.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 250, 50));

        Continue2.setBackground(new java.awt.Color(153, 255, 102));
        Continue2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Continue2.setForeground(new java.awt.Color(255, 255, 255));
        Continue2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Continue2.setText("Continue");
        Continue2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 3, true));
        Continue2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Continue2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Continue2.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dark.jpg")); // NOI18N
        Continue2.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Continue2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Continue2StateChanged(evt);
            }
        });
        Continue2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Continue2FocusGained(evt);
            }
        });
        Continue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Continue2ActionPerformed(evt);
            }
        });
        SignInGreek.add(Continue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\FullLogo.jpg")); // NOI18N
        SignInGreek.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 10, 1180, 980));

        myTabs.addTab("Σύνδεση", SignInGreek);

        InfosGr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameGr.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        usernameGr.setText("Ψευδόνυμο :");
        InfosGr.add(usernameGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        userIn.setText("...");
        InfosGr.add(userIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 30));

        maleGr.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(maleGr);
        maleGr.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        maleGr.setText("Άνδρας");
        maleGr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maleGr.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dot.png")); // NOI18N
        maleGr.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\arrow.png")); // NOI18N
        maleGr.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\check.png")); // NOI18N
        InfosGr.add(maleGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 100, 20));

        femaleGr.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(femaleGr);
        femaleGr.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        femaleGr.setText("Γυναίκα");
        femaleGr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        femaleGr.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dot.png")); // NOI18N
        femaleGr.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\arrow.png")); // NOI18N
        femaleGr.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\check.png")); // NOI18N
        InfosGr.add(femaleGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 100, 20));

        otherGr.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(otherGr);
        otherGr.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        otherGr.setText("Άλλο");
        otherGr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGr.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dot.png")); // NOI18N
        otherGr.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\arrow.png")); // NOI18N
        otherGr.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\check.png")); // NOI18N
        InfosGr.add(otherGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 80, 20));

        ageGr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 2, true));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "17", "18", "19", "20", "21", "22", "23", "24+" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ageGr.setViewportView(jList1);

        InfosGr.add(ageGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 90, 80));

        Next1.setBackground(new java.awt.Color(153, 255, 102));
        Next1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Next1.setForeground(new java.awt.Color(255, 255, 255));
        Next1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Next1.setText("Next");
        Next1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 3, true));
        Next1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Next1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dark.jpg")); // NOI18N
        Next1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Next1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Next1StateChanged(evt);
            }
        });
        Next1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Next1FocusGained(evt);
            }
        });
        Next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next1ActionPerformed(evt);
            }
        });
        InfosGr.add(Next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 140, 40));

        birth.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        birth.setText("Ηλικία :");
        InfosGr.add(birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 80, -1));

        genderGr.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        genderGr.setText("Φύλλο :");
        InfosGr.add(genderGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 70, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\FullLogo.jpg")); // NOI18N
        InfosGr.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 1160, 950));

        myTabs.addTab("tab4", InfosGr);

        InfosEn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameEn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        usernameEn.setText("Username :");
        InfosEn.add(usernameEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 90, -1));

        UserIn2.setText("...");
        InfosEn.add(UserIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 30));

        otherEn.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(otherEn);
        otherEn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        otherEn.setText("Other");
        otherEn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherEn.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dot.png")); // NOI18N
        otherEn.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\arrow.png")); // NOI18N
        otherEn.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\check.png")); // NOI18N
        otherEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherEnActionPerformed(evt);
            }
        });
        InfosEn.add(otherEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 110, 20));

        maleEn.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(maleEn);
        maleEn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        maleEn.setText("Man");
        maleEn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maleEn.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dot.png")); // NOI18N
        maleEn.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\arrow.png")); // NOI18N
        maleEn.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\check.png")); // NOI18N
        InfosEn.add(maleEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 100, 20));

        womanEn.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(womanEn);
        womanEn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        womanEn.setText("Woman");
        womanEn.setToolTipText("");
        womanEn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        womanEn.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dot.png")); // NOI18N
        womanEn.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\arrow.png")); // NOI18N
        womanEn.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\check.png")); // NOI18N
        InfosEn.add(womanEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 100, 20));

        ageEn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 2, true));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "17", "18", "19", "20", "21", "22", "23", "24+" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ageEn.setViewportView(jList2);

        InfosEn.add(ageEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 90, 80));

        Next2.setBackground(new java.awt.Color(153, 255, 102));
        Next2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Next2.setForeground(new java.awt.Color(255, 255, 255));
        Next2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Next2.setText("Next");
        Next2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 3, true));
        Next2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Next2.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\dark.jpg")); // NOI18N
        Next2.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\green3.png")); // NOI18N
        Next2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Next2StateChanged(evt);
            }
        });
        Next2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Next2FocusGained(evt);
            }
        });
        Next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next2ActionPerformed(evt);
            }
        });
        InfosEn.add(Next2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 140, 40));

        age2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        age2.setText("Age :");
        InfosEn.add(age2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 80, -1));

        genderEn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        genderEn.setText("Gender :");
        InfosEn.add(genderEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 80, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\ExceDriving\\FullLogo.jpg")); // NOI18N
        InfosEn.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 1160, 950));

        myTabs.addTab("tab4", InfosEn);

        getContentPane().add(myTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -32, 890, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GreekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreekActionPerformed
        myTabs.setSelectedIndex(2);
    }//GEN-LAST:event_GreekActionPerformed

    private void gmailAPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailAPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmailAPIActionPerformed

    private void EnglishStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EnglishStateChanged
        
    }//GEN-LAST:event_EnglishStateChanged

    private void myTabsComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_myTabsComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_myTabsComponentHidden

    private void EnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishActionPerformed
       myTabs.setSelectedIndex(1);
   
    }//GEN-LAST:event_EnglishActionPerformed

    private void EnglishFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnglishFocusGained
        
    }//GEN-LAST:event_EnglishFocusGained

    private void Continue1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Continue1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Continue1StateChanged

    private void Continue1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Continue1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Continue1FocusGained

    private void Continue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue1ActionPerformed
       myTabs.setSelectedIndex(4);
    }//GEN-LAST:event_Continue1ActionPerformed

    private void Continue2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Continue2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Continue2StateChanged

    private void Continue2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Continue2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Continue2FocusGained

    private void Continue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue2ActionPerformed
        myTabs.setSelectedIndex(3);
    }//GEN-LAST:event_Continue2ActionPerformed

    private void Next1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Next1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Next1StateChanged

    private void Next1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Next1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Next1FocusGained

    private void Next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Next1ActionPerformed

    private void Next2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Next2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Next2StateChanged

    private void Next2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Next2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Next2FocusGained

    private void Next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Next2ActionPerformed

    private void otherEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherEnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
                
               
            
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue1;
    private javax.swing.JButton Continue2;
    private javax.swing.JButton English;
    private javax.swing.JButton Greek;
    private javax.swing.JPanel InfosEn;
    private javax.swing.JPanel InfosGr;
    private javax.swing.JPanel Language;
    private javax.swing.JButton Next1;
    private javax.swing.JButton Next2;
    private javax.swing.JPanel SignIn;
    private javax.swing.JPanel SignInGreek;
    private javax.swing.JTextField UserIn2;
    private javax.swing.JTextField age;
    private javax.swing.JLabel age2;
    private javax.swing.JScrollPane ageEn;
    private javax.swing.JScrollPane ageGr;
    private javax.swing.JLabel birth;
    private javax.swing.JRadioButton female;
    private javax.swing.JRadioButton femaleGr;
    private javax.swing.JLabel genderEn;
    private javax.swing.JLabel genderGr;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JButton gmailAPI;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton maleEn;
    private javax.swing.JRadioButton maleGr;
    private javax.swing.JTabbedPane myTabs;
    private javax.swing.JButton nextInfo;
    private javax.swing.JRadioButton other;
    private javax.swing.JRadioButton otherEn;
    private javax.swing.JRadioButton otherGr;
    private javax.swing.JTextField user;
    private javax.swing.JTextField userIn;
    private javax.swing.JLabel username;
    private javax.swing.JLabel usernameEn;
    private javax.swing.JLabel usernameGr;
    private javax.swing.JRadioButton womanEn;
    // End of variables declaration//GEN-END:variables

    private static class Jbutton extends JButton {

        public Jbutton() {
        }
    }
}
